services:

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
     - ./data:/app/data
     - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    restart: always

  
  dashboard:
    build: .
    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always


  prefect-server:
    image: prefecthq/prefect:3.8.1-python3.13
    command: prefect server start --host 0.0.0.0 --port 4200
    environment:
      - PREFECT_HOME=/opt/prefect
      - PREFECT_UI_API_URL=http://192.168.0.41:4200/api
    volumes:
      - prefect-data:/opt/prefect
    ports: ["4200:4200"]
    restart: always


  prefect-worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    command: prefect worker start -p process-pool
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
     - ./data:/app/data
     - ./mlruns:/app/mlruns
    restart: always
    depends_on: 
      - prefect-server


volumes:
  prefect-data:
